# Generated by Django 5.0.1 on 2024-01-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
    ]
